apiVersion: apps/v1
kind: Deployment
metadata:
  name: twodo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twodo-backend
  template:
    metadata:
      labels:
        app: twodo-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
        env:
        # --- בניית הכתובת למסד הנתונים ---
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: twodo-secrets
              key: db-url
        # הזרקת היוזר והסיסמה בנפרד ליתר ביטחון
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: twodo-secrets
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: twodo-secrets
              key: db-password
        ports:
        - containerPort: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: twodo-backend
  ports:
  - port: 80
    targetPort: {{ .Values.backend.port }}