apiVersion: apps/v1
kind: Deployment
metadata:
  name: twodo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twodo-frontend
  template:
    metadata:
      labels:
        app: twodo-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: twodo-frontend
  ports:
  - port: 80
    targetPort: {{ .Values.frontend.port }}